### PR TITLE
Use jhipster-dependencies

### PR DESCRIPTION
**Pull request by erikkemperman**
Of course this fails on Travis because the `jhipster-dependencies` artifact isn't published yet :-)

### CODE REVIEW

**Comment by jdubois** [comment]
I could release a v0.0.1 version just to do tests, WDYT?

**Comment by erikkemperman** [comment]
That would be great! I wasn't sure about the version number to choose, but I aligned it with server lib because that seemed to be what @Tcharl aimed for. But perhaps decoupling would be better... Let me know what you publish it as, and I will amend this PR accordingly?

**Comment by erikkemperman** [comment]
Actually hold on one sec, going to propose a little change to jhipster-dependencies, would be better to include them in release I think.

**Comment by erikkemperman** [comment]
Ok, that's done: https://github.com/jhipster/jhipster-dependencies/pull/4

**Comment by erikkemperman** [comment]
@jdubois So I have one more PR on jhipster-dependencies, but it's not really critical for integration:
https://github.com/jhipster/jhipster-dependencies/pull/5

Please let me know if you have time to make a preliminary release for testing purposes, and then I can amend this PR.

Thanks!

**Comment by jdubois** [comment]
For the jhipster-dependencies versions: at the moment I'd rather use 0.0.1 as we are just testing, and we will probably have several iterations before it's stable.
And I'm not sure it's good to tie both projects with the same version, they could have different lifecycles.

**Comment by erikkemperman** [comment]
Agreed, can you make that change and release? Thx!

**Comment by jdubois** [comment]
Hopefully it should appear here: http://repo1.maven.org/maven2/io/github/jhipster/
(I'm making some configuration changes to do the release, so I'll do a v0.0.2 very soon)

**Comment by erikkemperman** [comment]
Excellent! I will take a look this evening and use the latest version I find.

**Comment by erikkemperman** [comment]
@jdubois Amended to use 0.0.2, Travis passing!

**Comment by erikkemperman** [comment]
FYI Bumped jhipster-dependencies to 0.0.5, this is ready as far as I can tell!

**Comment by erikkemperman** [comment]
@jdubois Could you take a quick look at the PRs in jhipster-dependencies and merge & release if you like them? Would be good to then amend this PR to the latest release and use jhipster-dependencies throughout the jhipster projects, IMHO.

**Comment by jdubois** [comment]
Thanks @erikkemperman yes this looks good, just need to increase the jhipster-dependencies version number

**Comment by erikkemperman** [comment]
Thanks Julien!

**Pull request merged**
