### PR TITLE
Downgrade Cassandra-Unit-Spring to 2.2.2.1

### PR DESCRIPTION
**Pull request by SudharakaP**
Fixes https://github.com/jhipster/generator-jhipster/issues/11169

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
LGTM, it can be merged as soon as the CI pass

**Comment by pascalgrimaud** [comment]
I'll do a patch release today with this fix, then I can focus on preparing the next release of generator-jhipster with SB2.2

**Comment by ctamisier** [comment]
Excellent !
By the way it seems that cassandraunit is only used to load csv through CQLDataSet.
We don't use anymore its embedded part as we now use testcontainers.
By including spring-cassandra-unit, this pulls cassandra-unit which pulls cassandra-all (the cassandra server), and it's not used.

**Comment by pascalgrimaud** [comment]
Ok then, it can be an enhancement which can be doable in another ticket / pull request
would you want to do it @ctamisier plz ?

**Comment by ctamisier** [comment]
Sure !

**Comment by SudharakaP** [comment]
@ctamisier : Do you mean removing the cassandra-unit-spring dependency altogether?

**Comment by pascalgrimaud** [comment]
@SudharakaP : the jhipster lib is released, 3.4.0 !

**Comment by ctamisier** [comment]
@SudharakaP : Yes, it is just used to load CQL statements through `dataLoader.load(new ClassPathCQLDataSet(cqlDir + fileName, false, false, CASSANDRA_UNIT_KEYSPACE));`

Before we used EmbeddedCassandraServerHelper.startEmbeddedCassandra() from cassandra-unit but we migrated to testcontainers (https://github.com/jhipster/generator-jhipster/commit/99513878893c9729e575ba8ff00f8020a6ce46aa)

**Pull request merged**
