### PR TITLE
Upgrade Spring Cloud to Finchley.RELEASE

### PR DESCRIPTION
**Pull request by erikkemperman**
@jdubois Maybe this can make it in JH5?

Everything seems to work, but it needs an extra dependency in the generator (for microservices only). With that little change, it looks as though everything passes.

https://github.com/erikkemperman/generator-jhipster/commit/87667ec8e53f70a368ef98747532080a3efd4104

If you wish to proceed with this, please merge and release, and then I'll make a PR for the generator to bump to the new jhipster-dependencies version and add this extra dependency as well (or feel free to copy/paste the change manually, it's small enough).

### CODE REVIEW

**Comment by erikkemperman** [comment]
@jdubois Or if you wait just a little bit, I am currently testing a few other minor dependency bumps, in case you like to include those as well.

https://travis-ci.org/erikkemperman/jhipster/builds/394061542

**Comment by jdubois** [comment]
OK this is definitely worth the wait, but I need to release tomorrow, the day before JHispter Conf!!!!

**Comment by erikkemperman** [comment]
Cool, I just made that other [PR](https://github.com/jhipster/jhipster/pull/79). As far as I am concerned, both could be merged and released as 2.0.13 and then I can patch the generator as well!

**Comment by erikkemperman** [comment]
FYI the failing Travis builds are due to the missing dependency I mentioned, easily fixed. I have the PR for the generator ready, once jhipster/jhipster is merged and released.

**Comment by jdubois** [comment]
Thanks @erikkemperman - I'm going to merge everything I can, and try to have some stable builds during the night, so we can release tomorrow

**Comment by erikkemperman** [comment]
Great! I will be traveling tomorrow (yay Paris!) so I might not be online much... Here is the branch that I would submit to the generator to accommodate the changes in jhipster-dependencies; feel free to pick and choose if you like:

https://github.com/erikkemperman/generator-jhipster/commits/cloud-finchley

**Pull request merged**
