### PR TITLE
Fix range filtering on referring entity

### PR DESCRIPTION
**Pull request by Blackdread**
Hi,I propose these changes to QueryService to solve issue to have range filtering for referring entity.
Pull request relates to issue [7195](https://github.com/jhipster/generator-jhipster/issues/7195).

For range filtering methods, I used **buildReferringEntitySpecification**, do you prefer **buildRangeReferringEntitySpecification** ? So it does not add this feature by default so user have to manually edit generated filter service classes to use the range filtering?

I used **root.get(reference)** for SingularAttribute but **root.join(reference)** for SetAttribute

@jdubois @gzsombor @DanielFran

### CODE REVIEW

**Comment by DanielFran** [comment]
@Blackdread that was exactly what I needed for existing database with composite keys.

As soon as this is available the dev can chose to change the generated code to adapt for his needs.

So it is OK for me like that.

Thanks.

**Comment by Blackdread** [comment]
I have rebased my previous pull request to latest jhipster master commit. Hope I did it well

**Comment by gzsombor** [comment]
Not really, it currently shows that you trying to push 214 commits in 92 changed files. 😢

**Comment by Blackdread** [comment]
What should I do?
I delete my fork repository and fork again and do a new pull request?

**Comment by Blackdread** [comment]
I created another pull request #49 so maybe can close this one?

**Comment by jdubois** [comment]
Yes OK, thanks @Blackdread !

**Pull request closed without merging**
