### PR TITLE
Make host and scheme configurable via properties

### PR DESCRIPTION
**Pull request by deepu105**
To enable configuring host and scheme for Swagger especially when working with HTTPS where swagger doesnt apply correct protocol

### CODE REVIEW

**Comment by deepu105** [comment]
@jdubois can you release this when you have time? I need this for my project

**Comment by jdubois** [comment]
I'm doing this now, but don't forget to update http://www.jhipster.tech/common-application-properties/ accordingly

**Comment by jdubois** [comment]
Release v1.1.10 done, you just need to wait for Maven central to sync :-)

**Comment by jdubois** [comment]
With all your hard work on the project, you deserve premium support!

**Comment by jdubois** [comment]
With all your hard work on the project, you deserve premium support!

**Comment by jdubois** [comment]
@deepu105 this makes the build fail if the new parameters are not initialized - I know it's not logical as the other properties (like termsOfServiceUrl) can be null, but that's how Swagger is coded.
I'm fixing this.

**Comment by deepu105** [comment]
Sorry about that the document doesn't say anything about it and I was blindly expecting it to behave the same. And i was in a hurry. My bad

**Pull request merged**
