### PR TITLE
Add Sonar Coverage

### PR DESCRIPTION
**Pull request by SudharakaP**
I saw that there's some problem with adding Sonar coverage at; https://github.com/jhipster/jhipster/commit/e08fbe71f1503add605876145242b138cde502ff and the discussion at; https://groups.google.com/forum/?hl=en#!topic/jhipster-dev/WY0AY05I7L8

I believe that there needs to be [at least one rule](https://github.com/jhipster/jhipster/pull/514/files#diff-600376dffeb79835ede4a0b285078036R171-R182) otherwise it seems to fail. So I've added it. Let me know if you guys see any issues. :smile: 

cc: @jdubois

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
Just tested it:
- the `mvn clean install -Dgpg.skip` works
- the coverage on Sonar is here

Everything is good. You rock @SudharakaP ! Thanks a lot

**Comment by SudharakaP** [comment]
@pascalgrimaud : You are most welcome. Glad it worked. :smile:

**Comment by jdubois** [comment]
Awesome work, thank you!

**Comment by SudharakaP** [comment]
@jdubois : My pleasure. :+1:

**Comment by pascalgrimaud** [comment]
@SudharakaP : the vote for you should be over, we just need to do official thing :)

**Comment by SudharakaP** [comment]
@pascalgrimaud : Ah, excited to hear that. :smiley:

**Pull request merged**
