### PR TITLE
Update some dependencies

### PR DESCRIPTION
**Pull request by DanielFran**

### CODE REVIEW

**Comment by DanielFran** [comment]
@jdubois Sorry, just to confirm with you if this PR is OK or I should delete it?
Thanks

**Comment by deepu105** [comment]
You dont have to delete any PR. We will review and merge or decline when
some of the core maintainers find the time.

Thanks & Regards,
Deepu

**Comment by jdubois** [comment]
Yes this all looks good - but did you test the MS SQL dependency upgrade? this is annoying to test....

**Comment by DanielFran** [comment]
I just create a project with mssql and did not found any issue.

**Comment by jdubois** [comment]
Thanks @DanielFran  let's merge this then

**Pull request merged**
