### PR TITLE
Add jhipster.api-docs.management-include-pattern property 

### PR DESCRIPTION
**Pull request by PierreBesson**
This change allow custom setting of the management docs include pattern

### CODE REVIEW

**Comment by DanielFran** [comment]
@PierreBesson this project is deprecated, you should switch to jhipster-bom project

@pascalgrimaud can you update the title to say it is deprecated?

**Comment by pascalgrimaud** [comment]
just done @DanielFran

**Comment by DanielFran** [comment]
@pascalgrimaud Can you pin jhipster-bom project instead of jhipster in the jhipster organisation page?

**Comment by pascalgrimaud** [comment]
Ok, will do after lunch

**Pull request closed without merging**
