### PR TITLE
Update spring-boot version to 2.1.3.RELEASE

### PR DESCRIPTION
**Pull request by DanielFran**

### CODE REVIEW

**Comment by jdubois** [comment]
This is making the build fail, it looks like Spring Boot 2.1.3 isn't released on Maven central -> I'm sorry @DanielFran but I am going to revert this for the moment

**Comment by DanielFran** [comment]
Seems fixed, the tests are green now.
Probably a glich in maven servers, since locally the dependecy was available...

**Comment by jdubois** [comment]
@DanielFran I'm afraid it's green because I rolled back your commit... are you sure?

**Comment by DanielFran** [comment]
@jdubois Yes, you can see on Travis logs that it makes the download of sb 2.1.3.

**Comment by pascalgrimaud** [comment]
We can try a new PR with sb 2.1.3 :-)

**Pull request merged**
