### PR TITLE
Externalize OAuth2 audience

### PR DESCRIPTION
**Pull request by vishal423**
Lib changes to fix https://github.com/jhipster/generator-jhipster/issues/10449

### CODE REVIEW

**Comment by DanielFran** [comment]
@vishal423 You have errors in test:
````sh
[INFO] Running io.github.jhipster.config.JHipsterPropertiesTest

[ERROR] Tests run: 69, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.122 s <<< FAILURE! - in io.github.jhipster.config.JHipsterPropertiesTest

[ERROR] testComplete  Time elapsed: 0.018 s  <<< ERROR!

java.lang.NoSuchMethodException: io.github.jhipster.config.JHipsterPropertiesTest.testSecurityOauth2Audience()

	at io.github.jhipster.config.JHipsterPropertiesTest.testComplete(JHipsterPropertiesTest.java:46)
````

**Comment by vishal423** [comment]
thanks @DanielFran I hope it should be good now

**Comment by vishal423** [comment]
It seems some unrelated issues in `(Test ngx-couchbase)` pipeline. Does anyone have an idea on what could be wrong with that (being stuck on backend tests for 60mins)?

**Comment by pascalgrimaud** [comment]
ngx-couchbase is broken with jdk8 for a while.
I didn't take the time to open a new ticket for that...

Then, LGTM, I think it can be merged

**Pull request merged**
