### PR TITLE
Update spring-boot version to 2.1.10.RELEASE and dependencies

### PR DESCRIPTION
**Pull request by DanielFran**

### CODE REVIEW

**Comment by DanielFran** [comment]
@pascalgrimaud The spring-boot release is on his way: https://github.com/spring-projects/spring-boot/releases

As soon as it is available in maven, I will update the 2 PR.
https://search.maven.org/search?q=g:org.springframework.boot%20AND%20a:spring-boot&core=gav

**Comment by pascalgrimaud** [comment]
@DanielFran : ok, don't hesitate to merge the appropriate PRs if you feel confident, so the full daily builds can run tomorrow :)

**Comment by pascalgrimaud** [comment]
@DanielFran : is it ready for a release ? I think it is

**Comment by DanielFran** [comment]
@pascalgrimaud Yes, it is

**Pull request merged**
