### PR TITLE
Bump spring-cloud to Finchley.RC2

### PR DESCRIPTION
**Pull request by erikkemperman**
Cf., https://github.com/jhipster/jhipster/pull/70#issuecomment-393045121

### CODE REVIEW

**Comment by jdubois** [comment]
OK I'm releasing a patch version for this

**Comment by erikkemperman** [comment]
Did you take a look at my other PR [here](https://github.com/jhipster/jhipster/pull/71)? If you don't like it or it needs improvement that's fine of course -- but otherwise perhaps it could be included in the release?

**Comment by erikkemperman** [comment]
Ah, nevermind, you did the release already. Sorry, I could have checked before I posted :)

**Comment by jdubois** [comment]
Yes of course, and it would be really good to get rid of Guava for "normal" users. But I saw we needed to wait for the next SpringFox release, so I'm waiting.

**Comment by jdubois** [comment]
yes @erikkemperman I totally agree, no problem :-)
and that's great :-)

**Pull request merged**
