### PR TITLE
Travis: fix builds after merge to jhipster

### PR DESCRIPTION
**Pull request by pascalgrimaud**
Thanks @erikkemperman
I took your `sed`, hope it's ok for you

Following discussion here https://github.com/jhipster/jhipster/pull/48

### CODE REVIEW

**Comment by erikkemperman** [comment]
@pascalgrimaud Yes, of course that's ok!

Couple of small suggestions:
- Maybe the logic for replacing versions could be in a separate script, so Julien can use same for releases?
- VERSION variable name might be too generic, maybe use a prefix?

**Comment by pascalgrimaud** [comment]
done!

**Comment by erikkemperman** [comment]
@pascalgrimaud Turns out that `sed` on macOS is slightly more finicky about flags and command-syntax. I'll make a PR to your branch, I think if you approve and merge it on your fork it should appear here automatically?

**Comment by pascalgrimaud** [comment]
Yes, you can to my fork and I will accept. It will update this PR.

Or I think you can push to this upstream pr too, but I don't remember how
Deepu did this lol

Le sam. 17 mars 2018 à 13:17, Erik Kemperman <notifications@github.com> a
écrit :

**Comment by erikkemperman** [comment]
I think I can only do that if the branch is on this repo, not a fork? Not really sure.

**Comment by ruddell** [comment]
Here's how Deepu explained to do it on a fork ([from the group email post](https://groups.google.com/forum/#!topic/jhipster-dev/tZ7byIkuO0w)):

```
>When I want to update someones PR, I do the below

# the branch name has to be same as the branch name used in the PR
gcb travis-after-merge-to-jhipster
git pull https://github.com/pascalgrimaud/generator-jhipster.git travis-after-merge-to-jhipster

# commit my changes
# push
git push https://github.com/pascalgrimaud/generator-jhipster.git travis-after-merge-to-jhipster
```

**Comment by pascalgrimaud** [comment]
Thanks @ruddell <3

**Comment by jdubois** [comment]
Guys, this is so complex, I'm just merging and trusting you, you both know this far better than me

**Comment by pascalgrimaud** [comment]
@jdubois : we add for you a shell script at root: `jhipster-version.sh` which will replace all versions correctly

So when you want release, you can:
- change the version: `./jhipster-version.sh X.Y.Z`
- do the release: commit, tag, deploy, etc.
- upgrade the version and add SNAPSHOT: `./jhipster-version.sh X.Y.Z+1-SNAPSHOT`

You can test this script:
- `./jhipster-version.sh 99.99.99`
- check the diff: `git diff`
- revert: `git checkout .`

**Pull request merged**
