### PR TITLE
WIP: Update to Spring boot 2.1.0.x & dependencies

### PR DESCRIPTION
**Pull request by DanielFran**

### CODE REVIEW

**Comment by jdubois** [comment]
Wow, lots of work @DanielFran !
Btw, isn't this time for you to join the core dev team? I'll open a vote if you're OK.

**Comment by DanielFran** [comment]
@jdubois Manny thanks to at least considering to include me in dev team.
It would be an honor!

**Comment by jdubois** [comment]
@DanielFran vote is open https://groups.google.com/forum/?hl=en#!topic/jhipster-dev/EvathgFXhpk :-)

**Comment by DanielFran** [comment]
@jdubois I add some issue when rebase this PR.
Will close this PR, create a new one just for some updated dependenties and then another one for spring-boot 2.1

**Pull request closed without merging**
