### PR TITLE
Reactive version of ResponseUtil

### PR DESCRIPTION
**Pull request by murdos**
This is needed for https://github.com/jhipster/generator-jhipster/pull/11416 and https://github.com/jhipster/generator-jhipster/issues/11404

### CODE REVIEW

**Comment by DanielFran** [comment]
@murdos Why create a specific ResponseUtil reactive classe and not reuse the existing?

**Comment by murdos** [comment]
@DanielFran : a non reactive JHipster project can't use an utility class that depends on Reactor, because it doesn't have the dependency. Thus it was necessary to use a distinct class.

**Comment by DanielFran** [comment]
Yes i saw it 😅😂🥱😴

**Comment by pascalgrimaud** [comment]
I plan to do a new release of jhipster dependencies (3.6.0)
Do you want to merge this @murdos ?

**Comment by murdos** [comment]
Yes, that would be nice, if there's no objection!

**Pull request merged**
