### PR TITLE
Info management endpoint improvements

### PR DESCRIPTION
**Pull request by PierreBesson**
Requirement for : https://github.com/jhipster/generator-jhipster/pull/7050

- Add git and maven build properties to /info endpoints (if build .properties files are on the classpath
- Add the active profiles to /info with a custom InfoContributor

### CODE REVIEW

**Comment by gmarziou** [comment]
@PierreBesson does it work with `--skip-git` option?

**Comment by pascalgrimaud** [comment]
@PierreBesson : I'll do my best to test and merge this. I understand that the build failed, and I don't see a proper way to automate the tests for these PR in this specific case.

**Comment by pascalgrimaud** [comment]
Nice work @PierreBesson !
For me, it works fine:

```yaml
{
  "display-ribbon-on-profiles": "dev",
  "git": {
    "commit": {
      "id": {
        "abbrev": "a9e1e98",
        "describe": "a9e1e98"
      }
    },
    "branch": "master"
  },
  "build": {
    "version": "0.0.1-SNAPSHOT",
    "artifact": "jhmono",
    "name": "Jhmono",
    "group": "io.github.pascalgrimaud",
    "time": "2018-04-02T16:26:02.164Z"
  },
  "activeProfiles": [
    "prod",
    "swagger"
  ]
}
```

**Comment by pascalgrimaud** [comment]
@PierreBesson : I did more tests tonight and saw some issues. You can look my Travis build, using this branch and your PR: https://travis-ci.org/pascalgrimaud/jhipster/builds/361251919

Here a resume of what it didn't work:

- for Gateway + Eureka:

```
curl http://localhost:8080/management/info
{
  "display-ribbon-on-profiles" : "dev"
}
```

So in this [code](https://github.com/PierreBesson/generator-jhipster/blob/3c266b051580006fc49baa009c243b9c7b979ecc/generators/client/templates/angular/src/main/webapp/app/layouts/profiles/profile.service.ts.ejs#L41), `pi.activeProfiles` is undefined, because `activeProfiles` doesn't exist

- for Consul, the application didn't start

I think there is a missing `:` in this code: https://github.com/PierreBesson/generator-jhipster/blob/3c266b051580006fc49baa009c243b9c7b979ecc/generators/server/templates/src/main/resources/config/bootstrap.yml.ejs#L46
`${info.project.version}` -> `${info.project.version:}`

- you need to check for React too

**Comment by PierreBesson** [comment]
@pascalgrimaud I think everything is OK now. But when I tried to sync branches across repos with Travis like you do it failed.

**Comment by pascalgrimaud** [comment]
> But when I tried to sync branches across repos with Travis like you do it failed.

It's because your branch didn't use jhipster-framework. You need to update your `remove-profile-resource-and-improve-info-endpoint`

**Comment by pascalgrimaud** [comment]
I think I fixed all issues.
I will PR to your branch @PierreBesson

**Comment by PierreBesson** [comment]
You are the best @pascalgrimaud !

**Comment by pascalgrimaud** [comment]
@PierreBesson : here my PR against your branch https://github.com/PierreBesson/jhipster/pull/1
Here the full Travis build: https://travis-ci.org/pascalgrimaud/jhipster/builds/369770495

**Comment by pascalgrimaud** [comment]
Here for the generator-jhipster: https://github.com/PierreBesson/generator-jhipster/pull/4

**Comment by PierreBesson** [comment]
Thanks a lot @pascamgrimaud for your efforts getting this merged. Finally we can get commit information in our build and info endpoint. The next step is to use this info to correctly tag the docker image.

**Comment by pascalgrimaud** [comment]
ahahaha, you're welcome !
But you should return to bed @PierreBesson, you need more sleep than me :laughing:

**Pull request merged**
