### PR TITLE
Review Sonar support

### PR DESCRIPTION
**Pull request by DanielFran**

### CODE REVIEW

**Comment by DanielFran** [comment]
@pascalgrimaud @jdubois Should we add this project also in https://sonarcloud.io/organizations/jhipster/projects ?

**Comment by pascalgrimaud** [comment]
It would be nice, but I'm afraid about the result :fearful:

**Comment by DanielFran** [comment]
And https://sonarcloud.io/dashboard?id=io.github.jhipster.sample%3Ajhipster-sample-application should be moved also to the organization?
And what about adding all samples?

**Comment by pascalgrimaud** [comment]
About moving to organization: yeah, something I had in mind since months
About all samples: we need to think about that, as other samples can changed regularly, by adding new entities in CI, changing options, etc. But sure, it will help to detect bad code

**Pull request merged**
