### PR TITLE
Migrate from Travis to Github Workflows

### PR DESCRIPTION
**Pull request by DanielFran**

### CODE REVIEW

**Comment by DanielFran** [comment]
Actually, it crashes in specific scrips 00-init-env.sh defined in the project due to specific TRAVIS variables.

@pascalgrimaud You help here is welcome.

**Comment by pascalgrimaud** [comment]
I'll have a look

**Comment by pascalgrimaud** [comment]
@DanielFran : sorry I'm a little late on this, but I don't forget it. I'll try to help as soon as possible, no worry

**Comment by pascalgrimaud** [comment]
@DanielFran : I found little time to work on it. I'll push directly my code into your branch if you're ok. So plz, don't rebase / force push :)

**Comment by DanielFran** [comment]
@pascalgrimaud Can this be merged?

**Comment by pascalgrimaud** [comment]
@DanielFran : yes, and we can remove Travis in another PR :)

**Pull request merged**
