### PR TITLE
Update to Cucumber 6

### PR DESCRIPTION
**Pull request by murdos**
See https://github.com/jhipster/generator-jhipster/issues/11136

### CODE REVIEW

**Comment by murdos** [comment]
@DanielFran : this will fail again, because I've not switched to generator branch here, and I don't think it's necessary. I've done it on generator side, and tests are passing.

**Comment by DanielFran** [comment]
@murdos Was just checking if errors were due to an old run... and since it was green in generator was expecting to validate it

**Comment by DanielFran** [comment]
So this seems ready. Do you want I switch on both project to master branch and merge it?

**Comment by murdos** [comment]
> 
> 
> So this seems ready. Do you want I switch on both project to master branch and merge it?

Thanks, but I'll do it right now ;)

**Pull request merged**
