### PR TITLE
 Update dependencies

### PR DESCRIPTION
**Pull request by DanielFran**

### CODE REVIEW

**Comment by DanielFran** [comment]
@jdubois @erikkemperman Can you please take a look?

**Comment by DanielFran** [comment]
@pascalgrimaud Can you please restart build?
Thanks

**Comment by DanielFran** [comment]
Seems OK now.

**Comment by pascalgrimaud** [comment]
@DanielFran : FYI, you can close / reopen the pull request, for restarting a build :)

**Comment by erikkemperman** [comment]
@DanielFran Thanks! Hopefully spring-cloud will be GA soon, I thought it was scheduled for end of April and aiming for spring-boot 2.0.1 but I was wrong (or they changed it):
https://github.com/spring-cloud/spring-cloud-release/milestone/39
https://github.com/spring-projects/spring-boot/milestone/109

By the way, we’re still not aligned with infinispan; stuck on 8.x while SB is managing 9.x versions. I couldn’t get the upgrade to work, would be good if someone who knows this better than me could take a look... If it helps I have WIP at
https://github.com/erikkemperman/jhipster/commits/upgrade-infinispan
https://github.com/erikkemperman/generator-jhipster/tree/upgrade-infinispan

**Comment by DanielFran** [comment]
@erikkemperman did you try with: https://mvnrepository.com/artifact/org.infinispan/infinispan-spring-boot-starter/2.0.0.Beta1

**Comment by erikkemperman** [comment]
@DanielFran Actually I was the one requesting that release :-)
https://github.com/infinispan/infinispan-spring-boot/issues/44
But I tried it briefly and it did not seem to solve the problems... I just don’t know about infinispan to debug it effectively!

**Pull request merged**
