### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by DanielFran**

### CODE REVIEW

**Comment by DanielFran** [comment]
@pascalgrimaud Can you help here with this issue, please?

https://travis-ci.org/jhipster/jhipster/jobs/534998110#L2529
> [ERROR] Failed to execute goal on project travis-couchbase-no-cache: Could not resolve dependencies for project io.github.jhipster.travis:travis-couchbase-no-cache:jar:0.0.1-SNAPSHOT: The following artifacts could not be resolved: com.couchbase.client:java-client:jar:2.7.5, com.couchbase.client:core-io:jar:1.7.5: Failure to find com.couchbase.client:java-client:jar:2.7.5 in http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced

I check on all maven repo and the dependencies are available!?!
Thanks

**Comment by pascalgrimaud** [comment]
@DanielFran : did you already restart the build ? if yes, I can try to delete the cache in Travis. If no, I can try to restart it

**Comment by DanielFran** [comment]
@pascalgrimaud I restarted 3 times the same test and always have the same issue.

**Comment by pascalgrimaud** [comment]
@DanielFran : I deleted all Travis cache at jhipster/jhipster, then I restarted the build and it still failed.

Then, I decided to test locally and it failed, exactly the same logs than Travis.
So the problem comes from the dependencies change here, not from Travis.

My logs:
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  13.158 s
[INFO] Finished at: 2019-05-21T16:39:47+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project travis-couchbase-no-cache: Could not resolve dependencies for project io.github.jhipster.travis:travis-couchbase-no-cache:jar:0.0.1-SNAPSHOT: The following artifacts could not be resolved: com.couchbase.client:java-client:jar:2.7.5, com.couchbase.client:core-io:jar:1.7.5: Could not find artifact com.couchbase.client:java-client:jar:2.7.5 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

16:39:50 in ~/tmp/28-couchbase on  master [!] took 16s 
```

Travis logs:

```
[INFO] --------< io.github.jhipster.travis:travis-couchbase-no-cache >---------
[INFO] Building Travis Couchbase No Cache 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.067 s
[INFO] Finished at: 2019-05-21T19:40:10+10:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project travis-couchbase-no-cache: Could not resolve dependencies for project io.github.jhipster.travis:travis-couchbase-no-cache:jar:0.0.1-SNAPSHOT: The following artifacts could not be resolved: com.couchbase.client:java-client:jar:2.7.5, com.couchbase.client:core-io:jar:1.7.5: Failure to find com.couchbase.client:java-client:jar:2.7.5 in http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
The command "$JHI_SCRIPTS/23-package.sh" exited with 1.
```

**Comment by DanielFran** [comment]
@pascalgrimaud This was an issue in the dependencies themselves.
They fixed it in a new version and now everything is OK.

**Comment by pascalgrimaud** [comment]
nice, good job @DanielFran !

**Pull request merged**
