### PR TITLE
Update version to 3.0.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by DanielFran**

### CODE REVIEW

**Comment by pvliss** [comment]
Hello @DanielFran. By bumping version to 3.0.0-SNAPSHOT then a new snapshot should be also pushed to nexus as well but I currently do not see it at https://oss.sonatype.org/content/repositories/snapshots/io/github/jhipster/jhipster-parent/. Have you already pushed it and maybe there's a delay? Anyways I currently build it locally but as you have also updated the generator then others might have issues as well. The CI builds properly as it points to the master branch I guess

**Comment by DanielFran** [comment]
Hello @pvliss, I did not push any snapshot to repository, I did not try because probably I did not have access.
@jdubois Can you please create a snapshot?
Thanks

**Comment by jdubois** [comment]
I'm sorry I didn't follow up... Doing a snapshot is a bit complex as in that case we need to reference the snapshot repo in the generator, and then remove it when we do a release. I can easily do a minor release, let me check what you are doing

**Comment by jdubois** [comment]
OK so I just pushed a "3.0.0-SNAPSHOT" to the snapshot repo - but I don't get why we suddenly have a major release, why the 3.0.0?

**Comment by DanielFran** [comment]
@jdubois It was defined to make a v2 maintenance for latest v2 available and spring-boot 2.1 branch would be the v3...

**Comment by DanielFran** [comment]
Now, i do not know why @pvliss needs this Snapshot version?

**Comment by jdubois** [comment]
Oh sorry I missed that. Anyway, it makes sense, for JHipster 6 I would like to move a few more things from the generator to the framework (so we generate less stuff), and that means a major version bump.

**Comment by pascalgrimaud** [comment]
@DanielFran : for current or new contributors :
- fork generator-jhipster
- clone your fork or update it
- generate a new jhipster project to start contributing
- launch it -> it will fail

See the stacktrace:

```
[ERROR]     'dependencies.dependency.version' for io.github.jhipster:jhipster-framework:jar is missing. @ line 134, column 21
[ERROR]     'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-cache:jar is missing. @ line 139, column 21
[ERROR]     'dependencies.dependency.version' for com.fasterxml.jackson.datatype:jackson-datatype-hibernate5:jar is missing. @ line 143, column 21
[ERROR]     'dependencies.dependency.version' for com.fasterxml.jackson.datatype:jackson-datatype-hppc:jar is missing. @ line 147, column 21
[ERROR]     'dependencies.dependency.version' for com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar is missing. @ line 151, column 21
[ERROR]     'dependencies.dependency.version' for com.fasterxml.jackson.module:jackson-module-afterburner:jar is missing. @ line 155, column 21
[ERROR]     'dependencies.dependency.version' for com.h2database:h2:jar is missing. @ line 739, column 29
[ERROR]     'dependencies.dependency.version' for com.jayway.jsonpath:json-path:jar is missing. @ line 164, column 21
[ERROR]     'dependencies.dependency.version' for io.springfox:springfox-swagger2:jar is missing. @ line 170, column 21
[ERROR]     'dependencies.dependency.version' for io.springfox:springfox-bean-validators:jar is missing. @ line 174, column 21
[ERROR]     'dependencies.dependency.version' for com.zaxxer:HikariCP:jar is missing. @ line 178, column 21
[ERROR]     'dependencies.dependency.version' for commons-io:commons-io:jar is missing. @ line 182, column 21
[ERROR]     'dependencies.dependency.version' for org.apache.commons:commons-lang3:jar is missing. @ line 186, column 21
[ERROR]     'dependencies.dependency.version' for javax.cache:cache-api:jar is missing. @ line 190, column 21
[ERROR]     'dependencies.dependency.version' for mysql:mysql-connector-java:jar is missing. @ line 194, column 21
[ERROR]     'dependencies.dependency.version' for org.assertj:assertj-core:jar is missing. @ line 198, column 21
[ERROR]     'dependencies.dependency.version' for org.ehcache:ehcache:jar is missing. @ line 203, column 21
[ERROR]     'dependencies.dependency.version' for org.hibernate:hibernate-jcache:jar is missing. @ line 207, column 21
[ERROR]     'dependencies.dependency.version' for org.hibernate:hibernate-jpamodelgen:jar is missing. @ line 211, column 21
[ERROR]     'dependencies.dependency.version' for org.hibernate:hibernate-core:jar is missing. @ line 216, column 21
[ERROR]     'dependencies.dependency.version' for org.hibernate:hibernate-envers:jar is missing. @ line 220, column 21
[ERROR]     'dependencies.dependency.version' for org.hibernate.validator:hibernate-validator:jar is missing. @ line 224, column 21
[ERROR]     'dependencies.dependency.version' for org.liquibase:liquibase-core:jar is missing. @ line 228, column 21
[ERROR]     'dependencies.dependency.version' for net.logstash.logback:logstash-logback-encoder:jar is missing. @ line 232, column 21
[ERROR]     'dependencies.dependency.version' for org.mapstruct:mapstruct:jar is missing. @ line 236, column 21
[ERROR]     'dependencies.dependency.version' for org.mapstruct:mapstruct-processor:jar is missing. @ line 240, column 21
[ERROR]     'dependencies.dependency.version' for org.springframework.boot:spring-boot-configuration-processor:jar is missing. @ line 245, column 21
[ERROR]     'dependencies.dependency.version' for org.springframework.boot:spring-boot-loader-tools:jar is missing. @ line 250, column 21
[ERROR]     'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-actuator:jar is missing. @ line 254, column 21
[ERROR]     'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-aop:jar is missing. @ line 258, column 21
[ERROR]     'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-data-jpa:jar is missing. @ line 262, column 21
[ERROR]     'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-logging:jar is missing. @ line 266, column 21
[ERROR]     'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-mail:jar is missing. @ line 270, column 21
[ERROR]     'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-security:jar is missing. @ line 274, column 21
[ERROR]     'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-thymeleaf:jar is missing. @ line 278, column 21
[ERROR]     'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-web:jar is missing. @ line 282, column 21
[ERROR]     'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-test:jar is missing. @ line 286, column 21
[ERROR]     'dependencies.dependency.version' for org.springframework.boot:spring-boot-test:jar is missing. @ line 291, column 21
[ERROR]     'dependencies.dependency.version' for org.springframework.security:spring-security-test:jar is missing. @ line 296, column 21
[ERROR]     'dependencies.dependency.version' for org.zalando:problem-spring-web:jar is missing. @ line 301, column 21
[ERROR]     'dependencies.dependency.version' for io.jsonwebtoken:jjwt-api:jar is missing. @ line 305, column 21
[ERROR]     'dependencies.dependency.version' for io.jsonwebtoken:jjwt-impl:jar is missing. @ line 309, column 21
[ERROR]     'dependencies.dependency.version' for io.jsonwebtoken:jjwt-jackson:jar is missing. @ line 314, column 21
[ERROR]     'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-cloud-connectors:jar is missing. @ line 320, column 21
[ERROR]     'dependencies.dependency.version' for org.springframework.security:spring-security-data:jar is missing. @ line 325, column 21
[ERROR]     'dependencies.dependency.version' for io.micrometer:micrometer-registry-prometheus:jar is missing. @ line 329, column 21
[ERROR]     'dependencies.dependency.version' for io.dropwizard.metrics:metrics-core:jar is missing. @ line 333, column 21
[ERROR]     'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-undertow:jar is missing. @ line 730, column 29
[ERROR]     'dependencies.dependency.version' for org.springframework.boot:spring-boot-devtools:jar is missing. @ line 734, column 29
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
```

We didn't add documentation about forking https://github.com/jhipster/jhipster/ and launching `mvn clean install`
That's what @pvliss wanted to tell us

**Comment by DanielFran** [comment]
@pascalgrimaud Got it!
I usually fork also jhipster-bom and compile it locally....

**Pull request merged**
