### PR TITLE
Upgrade Couchmove to 2.0

### PR DESCRIPTION
**Pull request by tchlyah**
Add Full Text Search Option (see https://github.com/jhipster/generator-jhipster/pull/11421)

### CODE REVIEW

**Comment by DanielFran** [comment]
@tchlyah Maybe you can review couchbase-client version?

**Comment by mraible** [comment]
This seems to cause a compilation failure in couchbase + elasticsearch + oauth: https://github.com/jhipster/generator-jhipster/pull/11623/checks?check_run_id=618427010#step:14:53

**Comment by mraible** [comment]
Might be related: `org.apache.commons.codec.binary.Base64` is no longer available. https://github.com/jhipster/generator-jhipster/pull/11623/checks?check_run_id=618427114#step:14:185

**Comment by mraible** [comment]
I've confirmed that changing the `webflux-couchbase` project to use v1.1 fixes compilation:

```xml
<dependency>
    <groupId>com.github.differentway</groupId>
    <artifactId>couchmove</artifactId>
    <version>1.1</version>
</dependency>
```

Therefore, I'm reverting this change.

**Comment by tchlyah** [comment]
sorry @mraible I didn't saw your message soon enough. This update is meant for the Couchbase Full Text Search option, and https://github.com/jhipster/generator-jhipster/pull/11421 fixes the issue.

I don't think that reverting this is a good solution since we are using here a transitive dependency and we shouldn't rely on it, it's better to add directly the dependency as we do for cassandra. This what I did here https://github.com/jhipster/generator-jhipster/pull/11421/commits/a730bd20dbe58f3f2367612309faf66fa9d4c929.

I can separate the fix from the FTS PR if you don't want to wait for its review.

**Comment by murdos** [comment]
> I can separate the fix from the FTS PR if you don't want to wait for its review.

Yes, please do so, because currently `master` is broken.

**Comment by tchlyah** [comment]
Done in https://github.com/jhipster/generator-jhipster/pull/11640, it should be ok

**Comment by tchlyah** [comment]
> @tchlyah Maybe you can review couchbase-client version?

Done in https://github.com/jhipster/jhipster/pull/680

**Pull request merged**
