### PR TITLE
add kafka

### PR DESCRIPTION
**Pull request by ctamisier**

### CODE REVIEW

**Comment by DanielFran** [comment]
@pascalgrimaud Probably you already see it, we have currently issues with the Travis pipeline to install chrome: https://travis-ci.org/jhipster/jhipster/jobs/584232626#L593

**Comment by pascalgrimaud** [comment]
@DanielFran : yes, we need to apply the same patch we did in generator-jhipster -> https://github.com/jhipster/generator-jhipster/commits/master/.travis.yml

**Comment by pascalgrimaud** [comment]
I'm changing the label, we can merge this after the next release
I need to do more tests with this

**Comment by pascalgrimaud** [comment]
The build failed but it's normal as the generator-jhipster master need to contain https://github.com/jhipster/generator-jhipster/pull/10379
So I'm merging as I just tested it !

**Pull request merged**
