### PR TITLE
Revert "Bump couchbase-testcontainer from 1.3 to 1.12"

### PR DESCRIPTION
**Pull request by DanielFran**
Reverts jhipster/jhipster#209

### CODE REVIEW

**Comment by cbornet** [comment]
Why can't we use 1.12 ?

**Comment by DanielFran** [comment]
1.12 was created but were supposed to be 1.1.2!

https://search.maven.org/search?q=g:com.github.differentway%20AND%20a:couchbase-testcontainer&core=gav

The latest version is 1.3: https://github.com/differentway/testcontainers-java-module-couchbase/releases

**Comment by cbornet** [comment]
Oh ! The semantic versionning of couchbase-testcontainer is broken ! We should ask @tchlyah to publish a 1.13 version to fix this

**Comment by cbornet** [comment]
Or shouldn't wwe use the official module : org.testcontainers:couchbase:1.11.0 ?

**Comment by DanielFran** [comment]
In fact we are using org.testcontainers module for other cases.

@tchlyah Can you confirm what should be the approach, use the current module or the official?

Thanks

**Comment by cbornet** [comment]
I think the issues that @tchlyah fixed in his own project since he contributed to the main testcontainer repo have also been fixed there: https://github.com/testcontainers/testcontainers-java/pull/815 .
So it should be OK to switch.

**Comment by tchlyah** [comment]
Yes the version 1.12 is a beginner mistake, sorry for that. I tried to remove it but no luck. So the latest version is 1.3.

Yes I have contributed the main repo, I wanted to wait until it is stable since a lot of modifications have been made after my contribution. But I think now it is safe to migrate to the main library, I'll close mine after that.

Sorry I didn't find time to do the migration I'll try to do it ASAP.

**Comment by DanielFran** [comment]
Thanks @tchlyah we will then wait for your PR to migrate to official module.

**Comment by bsideup** [comment]
FYI our "official" Couchbase module received some attention from the Couchbase folks, they helped with the reviews and provided more info on port randomization and a few other topics.

I hope the upgrade will be painless and please report issues if any! :)

**Pull request merged**
