### PR TITLE
Fix builds, using JDK11

### PR DESCRIPTION
**Pull request by pascalgrimaud**

### CODE REVIEW

**Comment by DanielFran** [comment]
@pascalgrimaud Thanks for the changes.
Should we consider to switch from Travis to Github actions like in the generator project?

**Comment by pascalgrimaud** [comment]
Yes, it's the plan. But not enough time these last weeks :(

**Comment by pascalgrimaud** [comment]
@DanielFran : I'm merging this, so I can start the release for the jhipster lib

**Comment by pascalgrimaud** [comment]
I can't do a release right now, as https://oss.sonatype.org is down

**Pull request merged**
